{% set xorg_name = "imake" %}
{% set xorg_category = "util" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.11" %}
{% set sha256 = "55955527eaebe94633e4083d4fe5f2160a65fe4c6dafdee48b89fea5f1ca8a78" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0

requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - gnuconfig                    # [unix]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler("cxx") }}        # [unix]
    - {{ compiler("m2w64_cxx") }}  # [win]
  host:
    - xorg-util-macros
    - xorg-xorgproto

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org incarnation of the X11 IMake utility.'

extra:
  recipe-maintainers:
    - pkgw
