travis:
  secure:
    BINSTAR_TOKEN: uI62JIjS+oiwRdXNpNs6jVG8ERoztJCyNECMBmkPeq7dIZMzswjtck69dINHqImjlpfFS1vscBIHRALZI1FSvu414ewNoPp3ibwTJG5/MFw28nFuXjmqmapvMjjIkHhD/p8sofsF5IJr+AzMFDNDcqxWjV6uxYHNyyvtLsPkeubYK7eCe5RWawqyFn545hFIpIdT+B4CAylpOba6geeHSy0ve0tUWJaBaUPAO2LkuCtxpAgY9kuzzi1dRu5u8+H+assvRDpYbZ/du0J2z39JkEWv3E4SLwGCLPeJ4qZCKFarhDWAfI+3ScxBs84V2IzWiu5zd/CpAPaG8vj09vLHvWBxKuBn1/nQ6mUEqCI6W5Hs413+ojLg0AmGO93b5halm841pnhBSrrJ8BUAme8Jz/2a8w/KH5QAdHi4IRv9RUknne6eH8TzL56JqyRIUeNZpqDp1SdbDX/oe8sJwH7PN6/BldicGBQWge3j6sqxk0XgfnrQ3t2KIcNWfxpIyE/dG/9tIG9kwajlM7hH+89dI/u4/UAwpxzseV5+R64Sk/7pTspy/9MlA4KYUMIl/HpEZTTAnrATXL0WaNU7Qgz1rM4IeNHUvzIEutrh6wV8Cx6SwchtSpgnPapGBO1oQQsUAGM6g0RyKcpb2J57SARDqsbuGLjc0Oo7EYV20U7ij8k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
