travis:
  secure:
    BINSTAR_TOKEN: mswOW9TkXsW4VgE5/ACXLtYSqNMWapQAsAQ6LvQ7N8ly7GV54KHy9ckR+CBrxIbhYRWk4jJyAS274oAmWTU/EmZPK095aizqNFKICeVdyxNVrylc9qP8cdqdcKOzvgXylZAHrOpzodeJxPVWQ+EPPcDbcDTKZhGZyRInR9gJkSB1cUy2jARA5AF4OObDmdm7zPyvgsE5ooI6I7D3jDNbnwjIaKTuLQdQ9gADGx9br6W9wWFOub1OaMRQ8lY1tWE8JG+wgjrWvgXrr8RI3Buc6+X6HTQ6cdQh+OZ5TJ1tWUhDxosmPvDr3exU/t8Wmd9D2OpkY8ZvH+0al2NbmfjEaDBLwNC8c/O0rwsv6NkjIf0D+9VXnd0oUMsw+GxiTpqEuAp2UeWlGOXAYhFT00GqIA8o8N5SnR0NQbZFKsV0eo0HFreU8BGZsv+DHsV8o6Ge08NTJJcGJovoLmKyWAncPCDtmis5u1KwZmCoRstR9Q33JnJiZlVxQVVASSA8pLNw9j3weKDFSqS9REhUII/DZ/bOxVCrq5nnmp4Iq6jekaUdKTTcU7JxAKdY4mPXk6Wh/n/uaZb7D/8xt+diR1lSPHFlOBlQabV6VZTUey5L7v3A2DFli/jYq/kJJWT3nN4+mAi7Y2/b+YpfYEIRTpapF+jcco6vaZmd5eLUYowaRYk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
